SELECT *
FROM RECURSO AS R
INNER JOIN TIPOS_RECURSO AS TR ON R.COD_TIPO = TR.CODIGO
WHERE TR.NOMBRE = 'Pokeballs'


-- ¿Qué tipos de pokeball existen?

SELECT COUNT  (R.NOMBRE)
FROM TIPOS_RECURSO TR 
INNER JOIN RECURSO R ON R.COD_TIPO= TR.CODIGO
WHERE TR.NOMBRE = 'Pokeballs'


--FORMAS

SELECT TP.NOMBRE, COUNT(*) as "Número de Pokémons"
FROM POKEMON_FORMA AS PF
INNER JOIN TIPOS_POKEMON AS TP ON
PF.COD_TIPO_POKEMON_1 = TP.CODIGO
GROUP BY TP.CODIGO, TP.NOMBRE
ORDER BY "Número de Pokémons" DESC



--ETIMOLOGÍA


SELECT  P.NOMBRE, E.NOMBRE, E.DEFINICION_ES
FROM POKEMON AS P
INNER JOIN POK_ETIMOLOGIA AS PE ON P.CODIGO= PE.COD_POKEMON
INNER JOIN ETIMOLOGIA AS E ON PE.COD_ETIMOLOGIA =E.CODIGO
