SELECT P.CODIGO  AS "código", P.NOMBRE as "Pokémon", string_agg(E.NOMBRE, '; 'ORDER BY E.NOMBRE) AS "Especies"
FROM POKEMON AS P
INNER JOIN POKEMON_FORMA AS PF ON P.CODIGO =PF.COD_POKEMON
INNER JOIN ESPECIE AS E ON PF.COD_ESPECIE =E.CODIGO
WHERE P.GENERACION=1 AND P.CODIGO IN ( SELECT DISTINCT  COD_POKEMON
									 FROM POK_MOV_POR_HUEVOS)
									 AND (P.CODIGO IN (SELECT PF2.COD_POKEMON
												  FROM POKEMON_FORMA AS PF2 
													  INNER JOIN POK_FORMA_GENERO AS PFG ON PF2.ID= pfg.id_pok_forma
												  WHERE(PFG.GENERO='female' AND PFG.PORCENTAJE='100')) OR
												  P.CODIGO IN(SELECT PF2.COD_POKEMON FROM POKEMON_FORMA AS PF2
															 WHERE ID NOT IN (SELECT ID_POK_FORMA FROM POK_FORMA_GENERO)))
									 GROUP BY P.CODIGO, P.NOMBRE
									 ORDER BY  "Especies", P.NOMBRE ASC
