SELECT PF.NOMBRE, PFE.VALOR_MAXIMO
FROM POKEMON_FORMA AS PF 
INNER JOIN POK_FORMA_ESTADISTICO PFE ON PF.ID=PFE.ID_POK_FORMA
INNER JOIN ESTADISTICO AS E ON PFE.COD_ESTADISTICO =E.CODIGO
WHERE E.NOMBRE_ES = 'Ataque'
order by pfe.valor_maximo desc
limit 1